#!/bin/bash

if [ "$USER" != "robot" ] ; 
then
	echo 'FATAL: CAN ONLY BE EXECUTED AS "robot" USER'
	exit
fi

if [ "$HOSTNAME" != "$ROBOT-pc2" ] ; 
then
	echo "FATAL: CAN ONLY BE EXECUTED ON PC2"
	exit
fi

echo "Executing adduser"
sudo /usr/sbin/adduser $1 --home /u/$1

echo "Syncing passwd file to other cob-pcs"
sudo rsync -e ssh -avz /etc/passwd /etc/shadow /etc/group root@$ROBOT-pc1:/etc/
sudo rsync -e ssh -avz /etc/passwd /etc/shadow /etc/group root@$ROBOT-pc3:/etc/

echo "copy .bashrc"
sudo cp /u/robot/git/setup/cob-pcs/user.bashrc /u/$1/.bashrc
echo "done adding user"
