#!/bin/bash
export DISPLAY=:0 && dbus-monitor --session "type='signal',interface='org.gnome.ScreenSaver'" | \
(
  while true; do
    read X
    if echo $X | grep "boolean true" &> /dev/null; then
      echo SCREEN_LOCKED;
    elif echo $X | grep "boolean false" &> /dev/null; then
      sudo mount -a;
      sleep 1;
    fi
  done
)
