#!/bin/bash
#/****************************************************************
# *
# * Copyright (c) 2010
# *
# * Fraunhofer Institute for Manufacturing Engineering	
# * and Automation (IPA)
# *
# * +++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
# *
# * Project name: care-o-bot
# * ROS stack name:
# * ROS package name:
# * Description: This file creates and shows the dependency tree of the care-o-bot
# *     repository. Define all packages you want to include in the variables PACKAGES_XXX.
# * Usage:
# *     run "./showdeps" to create and show the dependency tree of all packages listed below
# *
# * +++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
# *			
# * Author: Florian Weisshardt, email:florian.weisshardt@ipa.fhg.de
# * Supervised by: Florian Weisshardt, email:florian.weisshardt@ipa.fhg.de
# *
# * Date of creation: Jan 2010
# * ToDo:
# *
# * +++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
# *
# * Redistribution and use in source and binary forms, with or without
# * modification, are permitted provided that the following conditions are met:
# *
# *     * Redistributions of source code must retain the above copyright
# *       notice, this list of conditions and the following disclaimer.
# *     * Redistributions in binary form must reproduce the above copyright
# *       notice, this list of conditions and the following disclaimer in the
# *       documentation and/or other materials provided with the distribution.
# *     * Neither the name of the Fraunhofer Institute for Manufacturing 
# *       Engineering and Automation (IPA) nor the names of its
# *       contributors may be used to endorse or promote products derived from
# *       this software without specific prior written permission.
# *
# * This program is free software: you can redistribute it and/or modify
# * it under the terms of the GNU Lesser General Public License LGPL as 
# * published by the Free Software Foundation, either version 3 of the 
# * License, or (at your option) any later version.
# * 
# * This program is distributed in the hope that it will be useful,
# * but WITHOUT ANY WARRANTY; without even the implied warranty of
# * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# * GNU Lesser General Public License LGPL for more details.
# * 
# * You should have received a copy of the GNU Lesser General Public 
# * License LGPL along with this program. 
# * If not, see <http://www.gnu.org/licenses/>.
# *
# ****************************************************************/

#--------------------------------------------------------------------
# list all packages here
PACKAGE_BRINGUP=\
cob_sick_s300,\
cob_bringup,\
cob_bringup_sim,\
cob_hardware_config,\
schunk_powercube_chain,\
schunk_hardware_config

PACKAGES_NAVIGATION=\
cob_2dnav,\
cob_2dslam

PACKAGES_MANIPULATION=\
cob_manipulator

PACKAGES_PERCEPTION=\
cob_people_detection,\
cob_people_detection_msgs,\
cob_object_detection,\
cob_object_detection_msgs,\
cob_3d_mapping_msgs,\
cob_3d_mapping_pipeline

PACKAGES_SCENARIOS=\
cob_fetch_and_carry,\
cob_wimicare

#--------------------------------------------------------------------
# choose stacks
if [ "$1" = "-b" ]; then
	PACKAGES=$PACKAGES_BRINGUP
elif [ "$1" = "-n" ]; then
	PACKAGES=$PACKAGES_NAVIGATION
elif [ "$1" = "-m" ]; then
	PACKAGES=$PACKAGES_MANIPULATION
elif [ "$1" = "-p" ]; then
	PACKAGES=$PACKAGES_PERCEPTION
elif [ "$1" = "-s" ]; then
	PACKAGES=$PACKAGES_SCENARIOS
else
	PACKAGES=$PACKAGES_BRINGUP,$PACKAGES_NAVIGATION,$PACKAGES_MANIPULATION,$PACKAGES_PERCEPTION,$PACKAGES_SCENARIOS
fi

echo $PACKAGES

# create dependency tree
rxdeps --one --cluster -l --target=$PACKAGES

# show dependency tree
evince deps.pdf&

