=== Basic system setup and configuration

==== Install Ubuntu 12.04 LTS "precise"
----
username: ipa
systemname: cob-stud-<client number>
password: ****
----


==== Update and upgrade your new operating system
----
$ sudo apt-get update
$ sudo apt-get upgrade
$ sudo apt-get dist-upgrade
$ sudo reboot
----
if you have problems with update than try the follow:
----
$ sudo rm /var/lib/apt/lists/* -vf
$ sudo apt-get update
----


==== Create "shared" directory on local client
----
$ sudo mkdir /share
$ sudo chmod -R a+rw /share
----


==== Create admin group
----
$ sudo addgroup admin
----


==== Create extra administrator account's
----
$ sudo adduser stud-admin --home /home-local/stud-admin 
$ sudo adduser stud-admin adm
$ sudo adduser stud-admin sudo
----
----
$ sudo adduser jenkins --home /home-local/jenkins
$ sudo adduser jenkins adm
$ sudo adduser jenkins sudo
----
Went to System Settings/User Accounts and add the new admin users as Admin's and give them their name.
After that logout from ipa account and login as stud-admin and delete the ipa account.


==== Gain root rights for admin user's
----
$ sudo nano /etc/sudoers
##add to the list###
stud-admin ALL=(ALL) NOPASSWD: ALL
jenkins    ALL=(ALL) NOPASSWD: ALL
----


==== Disable guest account
----
$ sudo nano /etc/lightdm/lightdm.conf
##add##
[SeatDefaults]
allow-guest=false
$ sudo restart lightdm
----


==== Remove the world readable permissions
----
$ sudo chmod 750 /home-local/stud-admin
$ sudo chmod 750 /home-local/jenkins
----


==== Enable root account
----
$ sudo passwd root
----

==== Enable shell auto-compl.
----
$ sudo nano /etc/bash.bashrc
----
and activate the follow lines:
----
if [ -f /etc/bash_completion ] && ! shopt -oq posix; then
    . /etc/bash_completion
fi
----

==== Add printer
First gain permission for admin user's
----
$ sudo -i
$ gpasswd -a stud-admin lp
$ gpasswd -a jenkins lp
----
printer ip-address: 10.0.1.99

==== Enable passwordless login for SSH
----
$ ssh-keygen
$ ssh-copy-id stud-admin@cob-kitchen-svr
----
login as jenkins
----
ssh-keygen
$ ssh-copy-id cob-jenkins-server
----

Login to stud-admin@cob-kitchen-svr and test if the following script works without throwing an error
----
$ ./git/setup/cob-stud-clients/cob-stud-install.sh vim
----


=== Driver installation

==== Graphiccard driver installation (nVidia)
----
$ sudo add-apt-repository ppa:ubuntu-x-swat/x-updates
$ sudo apt-get update
$ sudo apt-get install nvidia-current-dev
----


=== Install basic software

==== Adobe AcrobatReader
----
$ sudo apt-add-repository "deb http://archive.canonical.com/ $(lsb_release -sc) partner"
$ sudo apt-get update && sudo apt-get install flashplugin-installer acroread 
----

==== Basic software installation

Editors:
----
$ sudo apt-get install vim-gtk emacs gimp geany meshlab
----

Shells:
----
$ sudo apt-get install terminator zsh
----

Network:
----
$ sudo apt-get install openssh-server ntp curl portmap nfs-common
----

Commands:
----
$ sudo apt-get install tree wmctrl parallel
----

Additional linux packages and tools:
----
$ sudo apt-get install synaptic libpam-cracklib pbuilder debootstrap pigz htop gnome-system-tools
----

Development packages and tools:
----
$ sudo apt-get install libtbb-dev libsuitesparse-dev libxerces-c2-dev libtbb2 libann-dev libavcodec-extra-53
$ sudo apt-get install openjdk-6-jdk libvtk5-qt4-dev postgresql ipython octave pgadmin3 devscripts
----

Software:
----
$ sudo apt-get install eclipse meld gitg inkscape dia
----


=== Network configuration

==== Add proxy for apt
----
$ sudo nano /etc/apt/apt.conf.d/proxy
##add##
Acquire::http { Proxy "http://cob-jenkins-server:3142"; };
----


==== Setup nfs
----
$ sudo nano /etc/fstab
##add to the list##
cob-kitchen-nas:/volume1/home-nas    /home nfs rw,hard,intr   0   0
----


==== Config ldap clients

----
sudo apt-get install ldap-utils libpam-ldap libnss-ldap nslcd 
----

Select the following configuration for ldap:
----
Should debconf manage LDAP configuration? Yes
LDAP server Uniform Resource Identifier: ldap://10.0.1.1:390
Distinguished name of the search base: dc=ipa-apartment,dc=org
LDAP version to use: 3
Make local root Database admin: No
Does the LDAP database require login? Yes
Unprivileged database user: cn=zentyalro,dc=ipa-apartment,dc=org
Password for database login account: (Please ask nhg)
----

You can reconfigurate it with the command:

----
sudo dpkg-reconfigure ldap-auth-config
----

Select the following configuration for nslcd:
----
LDAP server URI: ldap://10.0.1.1:390
LDAP server search base: dc=ipa-apartment,dc=org
----
----
$ sudo vi /etc/nsswitch.conf
##append "ldap" word to the lines passwd, group and shadow##
# /etc/nsswitch.conf
passwd: compat ldap
group : compat ldap  
shadow: compat ldap 
hosts:     files mdns4_minimal [NOTFOUND=return] dns mdns4
networks:  files
protocols: db files
services:  db files
ethers:    db files
rpc:       db files
netgroup:  nis
sudoers:   ldap files
----

----
$ sudo vi /etc/pam.d/common-session
##add to the list##
session  optional     pam_mkhomedir.so skel=/etc/skel umask=0022
----

----
$ sudo vi /etc/lightdm/lightdm.conf
##add to the list##
greeter-show-manual-login=true
----

----
$ sudo vi /etc/pam.d/login
##add to the list##
session required pam_mkhomedir.so skel=/etc/skel umask=0022 
----

----
$ sudo vi /etc/pam.d/lightdm
##add to the list##
session required pam_mkhomedir.so skel=/etc/skel umask=0022
----

----
sudo update-rc.d nslcd enable
----


==== Setup ntp time synchronisation
----
$ sudo nano /etc/ntp.conf
##change server to##
server cob-kitchen-svr
----


=== Install ROS

==== Install ROS "fuerte" and "groovy" with environment
----
$ sudo sh -c 'echo "deb http://packages.ros.org/ros/ubuntu precise main" > /etc/apt/sources.list.d/ros-latest.list'
$ wget http://packages.ros.org/ros.key -O - | sudo apt-key add -
$ sudo apt-get update
----
----
$ sudo apt-get install ros-fuerte-desktop-full
$ sudo apt-get install ros-groovy-desktop-full
----
----
$ sudo rosdep init
$ rosdep update
----

Environment setup
----
###for fuerte###
$ echo "source /opt/ros/fuerte/setup.bash" >> ~/.bashrc
$ source ~/.bashrc
----
----
###for groovy###
$ echo "source /opt/ros/groovy/setup.bash" >> ~/.bashrc
$ source ~/.bashrc
----
if you just want to change the environment of your current shell, you can type:
----
###for fuerte###
$ source /opt/ros/fuerte/setup.bash
----
----
###for groovy###
$ source /opt/ros/groovy/setup.bash
----


==== Install additional tools
----
$ sudo apt-get install python-rosinstall python-rosdep
$ sudo apt-get install python-setuptools ogre-tools ros-groovy-diagnostics-monitors
$ sudo apt-get install ros-groovy-rxtools ros-groovy-pr2-* ros-groovy-client-rosjava-jni
$ sudo apt-get install ros-groovy-openni*
----
